server:
  port: 8093

spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5673

rabbit-config:
  order:
    exchange: x.order
    queue:
      name: q.order
      routing-key: order